---
label: default
hide_body: false
fields:
- type: datetime
  name: date
  label: Date
  config:
    display_utc: false
    required: true
- type: text
  config:
    required: true
  label: Title
  name: title
- type: file
  name: share_img
  label: share_img
- type: text
  name: slug
  label: slug
  config:
    required: true
pages:
- ikyoukoujitsu/content/post/coffee-break.md
- ikyoukoujitsu/content/post/銀杏とイルミネーション.md
- ikyoukoujitsu/content/post/よるさんぽ.md
